-- Criação da tabela TB_USER
CREATE TABLE IF NOT EXISTS TB_USER (
    id_user INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL
);

CREATE TABLE TB_CONTACT (
    id_contact INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    CPF VARCHAR(11) UNIQUE NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    cep VARCHAR(8) NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    id_user INT NOT NULL,
    FOREIGN KEY (id_user) REFERENCES TB_USER(id_user)
);
